version: "3.9"

services:
  redis:
    image: redis:7-alpine
    container_name: crm-ai-importer-redis

    ports:
      - "6379:6379"

    restart: unless-stopped

    volumes:
      - redis-data:/data

volumes:
  redis-data: